// Code generated by Slice Machine. DO NOT EDIT.

import Content from './Content';
import Divider from './Divider';
import Hero from './Hero';

export {
	Content,
	Divider,
	Hero,
};

export const components = {
	content: Content,
	divider: Divider,
	hero: Hero,
};
