// Code generated by Slice Machine. DO NOT EDIT.

import Content from './Content';
import Divider from './Divider';
import Hero from './Hero';
import MenuItem from './MenuItem';
import NewsletterSignup from './NewsletterSignup';

export {
	Content,
	Divider,
	Hero,
	MenuItem,
	NewsletterSignup,
};

export const components = {
	content: Content,
	divider: Divider,
	hero: Hero,
	menu_item: MenuItem,
	newsletter_signup: NewsletterSignup,
};
